name: Build docker image and push to Docker Hub

on:
  push:
#    tags:
#      - '**'
    paths:
      - 'ingredients/**'
      - '.github/workflows/*.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Initialize
        uses: actions/checkout@v2
      -
        run: |
          sudo apt update
          sudo apt install nodejs
      -
        run: sudo npm install -g @devcontainers/cli
      -
        name: Build image
        run: devcontainer build --workspace-folder ingredients --image-name ${{ github.repository }}:${{ github.ref_name }}
      -
        name: Login to registry (Docker Hub)
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Deploy image to registry
        run: docker push ${{ github.repository }}:${{ github.ref_name }}
      -
        name: Logout from registry
        run: docker logout
